# Generated by Django 6.0.4 on 2026-04-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_size', models.IntegerField(choices=[(5, '5x5'), (6, '6x6'), (7, '7x7'), (8, '8x8')], default=5)),
                ('game_mode', models.CharField(choices=[('PVP', 'Player vs Player'), ('PVA', 'Player vs AI')], default='PVA', max_length=3)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Level 1: Minimax (Demogorgon)'), (2, 'Level 2: Alpha-Beta (Demogorgon)'), (3, 'Level 3: A* Search (Shadowmonster)'), (4, 'Level 4: MCTS (Mindflayer)')], default=1)),
                ('current_turn', models.CharField(default='Player1', max_length=50)),
                ('is_over', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ELEVEN', 'Eleven'), ('DEMOGORGON', 'Demogorgon'), ('SHADOWMONSTER', 'Shadowmonster'), ('MINDFLAYER', 'Mindflayer')], max_length=50)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('has_powers', models.BooleanField(default=False)),
                ('is_ai', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='gameplay.game')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obstacle_type', models.CharField(choices=[('VEIN', 'Vein'), ('TRAP', 'Trap')], max_length=10)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacles', to='gameplay.game')),
            ],
        ),
    ]
