# Generated by Django 6.0.4 on 2026-04-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stuck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.CharField(default='ELEVEN', max_length=50),
        ),
    ]
