# Generated by Django 6.0.4 on 2026-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_character_stuck_alter_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('ELEVEN', 'Eleven'), ('DEMOGORGON', 'Demogorgon'), ('SHADOWMONSTER', 'Shadowmonster'), ('MINDFLAYER', 'Mindflayer')], default=None, max_length=50, null=True),
        ),
    ]
