# Generated by Django 6.0.4 on 2026-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='goal_x',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='game',
            name='goal_y',
            field=models.IntegerField(default=4),
        ),
    ]
