# Generated by Django 6.0.4 on 2026-04-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_game_goal_x_game_goal_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('ELEVEN', 'Eleven'), ('MAX', 'Max'), ('DEMOGORGON', 'Demogorgon'), ('SHADOWMONSTER', 'Shadowmonster'), ('MINDFLAYER', 'Mindflayer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('ELEVEN', 'Eleven'), ('MAX', 'Max'), ('DEMOGORGON', 'Demogorgon'), ('SHADOWMONSTER', 'Shadowmonster'), ('MINDFLAYER', 'Mindflayer')], default=None, max_length=50, null=True),
        ),
    ]
