# Generated by Django 6.0.4 on 2026-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_alter_character_name_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('PVP', 'Player vs Player'), ('PVA', 'Player vs AI'), ('P2VA', '2 Players vs AI')], default='PVA', max_length=4),
        ),
    ]
